### ISSUE TITLE
The specification of the horseshoe piror

### ISSUE THREAD

**Issue by jiahaoliu-ai** [mcol/hsstan#2]
I've looked into the specification of the horseshoe prior in the stan file "hs.stan". It seemed that you used a student t prior on tau and lambda as follows:

`lambda ~ student_t(nu, 0, 1);
tau ~ student_t(global_df, 0, global_scale * sigma)`

But from my current knowledge, the horseshoe prior on lambda and tau should be half cauchy instead of student t distribution. Can you clarify why the horseshoe prior are specified in the student t distribution in the hsstan package? Also, why the tau should be conditioned on the sigma?

**Comment by mcol** [comment]
This follows the specification provided in https://doi.org/10.1214/17-EJS1337SI. While originally the horseshoe prior was presented in terms of half cauchy, using a half t distribution is easier to sample, and the number or degrees of freedom `nu` allows to control the heaviness of the tails (see section 2.4). It turns out that a half t with `nu=1` corresponds to a half cauchy, so using the half t formulation is more general (see appendix C.1).

As for the relationship between tau and sigma, see section 3.2.

**Comment by jiahaoliu-ai** [comment]
Thanks a lot!
